replicaCount: 1

image:
  repository: nginx
  tag: 1.19.6
  pullPolicy: IfNotPresent

service:
  name: wndtnl-website
  type: NodePort
  externalPort: 8080
  internalPort: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi