replicaCount: 1

serviceAccount: pv-adidas-a

image:
  repository: nginx
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: pv-adidas-a
  type: NodePort
  externalPort: 8080
  internalPort: 80
