replicaCount: 1

serviceAccount: website

image:
  repository: nginx
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: website
  type: NodePort
  externalPort: 8080
  internalPort: 80
