---
apiVersion: v1
kind: Namespace
metadata:
  name: pv-adidas-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pv-adidas-a
  namespace: pv-adidas-a
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chart-deploy
  namespace: pv-adidas-a
rules:
  - apiGroups: ["", "apps"]
    resources:
    - namespaces
    - pods
    - deployments
    - services
    - secrets
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chart-deploy-binding
  namespace: pv-adidas-a
subjects:
  - kind: ServiceAccount
    name: pv-adidas-a
    namespace: pv-adidas-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chart-deploy