---
apiVersion: v1
kind: Namespace
metadata:
  name: website
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: website
  namespace: website
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: chart-deploy
  namespace: website
rules:
  - apiGroups: ["", "apps"]
    resources:
    - namespaces
    - pods    
    - deployments
    - services
    - secrets
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: chart-deploy-binding
  namespace: website
subjects:
  - kind: ServiceAccount
    name: website
    namespace: website
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chart-deploy